# Generated by Django 3.2.4 on 2021-07-18 13:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('child', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dose',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField()),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=5)),
                ('unit', models.CharField(choices=[('ml', 'ml'), ('drop', 'drop')], max_length=255)),
                ('first_day_from_birth', models.PositiveIntegerField()),
                ('last_day_from_birth', models.PositiveIntegerField()),
                ('booster', models.BooleanField(default=False)),
                ('compulsory_after_birth', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Vaccine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('route', models.TextField(blank=True, null=True)),
                ('site', models.TextField(blank=True, null=True)),
                ('side_effects', models.TextField(blank=True, null=True)),
                ('before_care', models.TextField(blank=True, null=True)),
                ('after_care', models.TextField(blank=True, null=True)),
                ('protect_against', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_vaccination', models.DateField(blank=True, null=True)),
                ('vaccinated', models.BooleanField(default=False)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='child.child')),
                ('dose', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vaccine.dose')),
            ],
        ),
        migrations.AddField(
            model_name='dose',
            name='vaccine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vaccine.vaccine'),
        ),
    ]
